// <auto-generated />
using System;
using AsyncWarehouse.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WarehouseMS.Infrastructure;

#nullable disable

namespace AsyncWarehouse.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20260306155739_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AsyncWarehouse.Domain.Models.InventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PalletId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("PalletId");

                    b.ToTable("InventoryItems");

                    b.HasDiscriminator<string>("ItemType").HasValue("InventoryItem");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("AsyncWarehouse.Domain.Models.Pallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float>("MaxCapacity")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Pallets");
                });

            modelBuilder.Entity("AsyncWarehouse.Domain.Models.Chemicals", b =>
                {
                    b.HasBaseType("AsyncWarehouse.Domain.Models.InventoryItem");

                    b.Property<DateTimeOffset>("ExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Hazard")
                        .HasColumnType("integer");

                    b.Property<float>("VolumeLiters")
                        .HasColumnType("real");

                    b.HasDiscriminator().HasValue("Chemical");
                });

            modelBuilder.Entity("AsyncWarehouse.Domain.Models.Electronics", b =>
                {
                    b.HasBaseType("AsyncWarehouse.Domain.Models.InventoryItem");

                    b.Property<float>("PowerWatts")
                        .HasColumnType("real");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WarrantyMonths")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Electronics");
                });

            modelBuilder.Entity("AsyncWarehouse.Domain.Models.Furniture", b =>
                {
                    b.HasBaseType("AsyncWarehouse.Domain.Models.InventoryItem");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("RequiresAssembly")
                        .HasColumnType("boolean");

                    b.HasDiscriminator().HasValue("Furniture");
                });

            modelBuilder.Entity("AsyncWarehouse.Domain.Models.InventoryItem", b =>
                {
                    b.HasOne("AsyncWarehouse.Domain.Models.Pallet", null)
                        .WithMany("Items")
                        .HasForeignKey("PalletId");
                });

            modelBuilder.Entity("AsyncWarehouse.Domain.Models.Furniture", b =>
                {
                    b.OwnsOne("AsyncWarehouse.Domain.Enums.Dimension", "Dimensions", b1 =>
                        {
                            b1.Property<Guid>("FurnitureId")
                                .HasColumnType("uuid");

                            b1.Property<float>("Height")
                                .HasColumnType("real");

                            b1.Property<float>("Length")
                                .HasColumnType("real");

                            b1.Property<float>("Width")
                                .HasColumnType("real");

                            b1.HasKey("FurnitureId");

                            b1.ToTable("InventoryItems");

                            b1.WithOwner()
                                .HasForeignKey("FurnitureId");
                        });

                    b.Navigation("Dimensions")
                        .IsRequired();
                });

            modelBuilder.Entity("AsyncWarehouse.Domain.Models.Pallet", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
